springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
  packages-to-scan: com.srdelsalto.todobackend.swagger.controllers
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/todo?useSSL=false
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update