import Navbar from "@/components/Navbar";
import "./globals.css";
import { TaskProvider } from "@/context/TasksContext";

export const metadata = {
  title: "Todo List Next App",
  description:
    "Generated by create next app and Programmed by Santiago Del Salto",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TaskProvider>
          <Navbar />
          {children}
        </TaskProvider>
      </body>
    </html>
  );
}
